language: node_js
node_js:
  - lts/*
install:
  - npm install -g firebase-tools
  - npm install -g lerna
  - lerna bootstrap
script:
  - npm run lint
  - npm run test
cache: npm
before_deploy:
  - npm install -g firebase-tools
  - echo 'About to deploy live...'
  - npm run build
deploy:
  - provider: firebase
    skip_cleanup: true
    on:
      branch: develop
    token:
      secure: $FIREBASE_DEV_TOKEN
    project: "whats-for-dinner-id"
  - provider: firebase
    skip_cleanup: true
    on:
      branch: master
    token:
      secure: $FIREBASE_PROD_TOKEN
    project: "plan-your-meals"
