language: node_js
node_js:
  - lts/*
install:
  - npm install -g firebase-tools
  - npm install -g lerna
  - lerna bootstrap
script:
  - npm run lint
cache: npm
before_deploy:
  - npm install -g firebase-tools
  - echo 'About to deploy live...'
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    tags: true
    branch: master
  token:
    secure: $FIREBASE_TOKEN
  project: "whats-for-dinner-id"