language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "whats-for-dinner-id"