language: node_js
node_js:
  - "10"
install:
  - npm install -g firebase-tools
  - npm install -g lerna
  - lerna bootstrap
script:
  - npm run lint
  - npm run test
cache: npm
before_deploy:
  - npm install -g firebase-tools
  - echo 'About to deploy live...'
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: firebase deploy -f --project "whats-for-dinner-id" --token "$FIREBASE_DEV_TOKEN"
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: firebase deploy -f --project "plan-your-meals" --token "$FIREBASE_PROD_TOKEN"
    on:
      branch: master
