language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run lint
cache:
  directories:
    - "node_modules"
before_deploy:
  - npm install -g firebase-tools
  - echo 'About to deploy live...'
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: $FIREBASE_TOKEN
  project: "whats-for-dinner-id"